### ISSUE TITLE
报错__init__() missing 1 required positional argument: 'num_labels'

### ISSUE THREAD

**Issue by Lingzhi-WANG** [real-brilliant/bert_chinese_pytorch#6]
Traceback (most recent call last):
  File "bert.py", line 651, in <module>
    main()
  File "bert.py", line 541, in main
    cache_dir=PYTORCH_PRETRAINED_BERT_CACHE / 'distributed_{}'.format(args.local_rank))
  File "/home/lindseywang/.local/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 581, in from_pretrained
    model = cls(config, *inputs, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'num_labels'

请问这是因为什么呢？

**Comment by Zhangpeixiang** [comment]
@LingzhiWang2017 在model中结尾添加num_labels=len(label_list)即可
